name: CI
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  go_build:
    runs-on: ubuntu-latest
    container: eversc/go-pr-checks:1.19
    steps:
      - name: go build
        run: |
          export GO111MODULE=on
          go build
