name: CI
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  go_build:
    runs-on: ubuntu-latest
    container: eversc/go-pr-checks:1.19
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: go build
        run: |
          export GO111MODULE=on
          go build
      - name: go fmt
        run: |
          test -z $(/usr/local/go/bin/gofmt -s -l $(find . -iname '*.go' -type f | grep -v /vendor/))
