name: CI
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci_block:
    runs-on: ubuntu-latest
    steps:
      - name: make empty commit to dependabot branch
        id: empty_dependabot
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh pr list -S 'author:app/dependabot' --json number -q '.[0].number'
