name: Update dependabot branch
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci_block:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make empty commit to dependabot branch
        id: empty_dependabot
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pr_number=$(gh pr list -S 'author:app/dependabot' --json number -q '.[0].number')
          gh pr view $pr_number --json headRefName -q '.headRefName'
